import React, {useEffect,useState} from "react";
import {motion,useScroll,useSpring,useTransform} from "framer-motion";
import {ArrowRight,ArrowUpRight,Check,ChevronDown,Code2,Cpu,Globe2,Layers3,Menu,Moon,Play,Sparkles,Sun,X,Zap,Quote} from "lucide-react";

const features=[
{icon:Cpu,title:"AI Automation",text:"Turn repetitive workflows into intelligent systems that keep moving without manual effort."},
{icon:Layers3,title:"Smart Analytics",text:"Transform live business signals into clear insights and decisions your team can act on."},
{icon:Zap,title:"Workflow Intelligence",text:"Connect tools, teams and data into faster workflows built around your goals."},
{icon:Globe2,title:"Predictive Insights",text:"Spot patterns early and make confident decisions with intelligent forecasting."}];
const testimonials=[
{quote:"Nexora helped us turn a complex workflow into something our entire team could understand and automate.",name:"Maya Chen",role:"Product Lead, Orbit"},
{quote:"The experience feels premium, fast and genuinely useful. Our team adopted it in days, not months.",name:"Daniel Brooks",role:"Founder, Northstar"},
{quote:"We finally have one intelligent layer connecting our data, workflows and decisions.",name:"Aisha Patel",role:"COO, Vertex"}];
const plans=[
{name:"Starter",price:"19",text:"For individuals exploring intelligent workflows.",items:["3 active workflows","Basic analytics","Community support"]},
{name:"Pro",price:"59",text:"For teams ready to automate and scale.",items:["Unlimited workflows","Advanced analytics","Priority support","AI predictions"],featured:true},
{name:"Enterprise",price:"149",text:"For organizations building at scale.",items:["Custom automation","Advanced security","Dedicated success team","Custom integrations"]}];

function Reveal({children,delay=0,className=""}){return <motion.div className={className} initial={{opacity:0,y:36}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.7,delay,ease:[.22,1,.36,1]}}>{children}</motion.div>}
function Counter({value,suffix=""}){const[count,setCount]=useState(0);useEffect(()=>{let frame,start;const tick=t=>{if(!start)start=t;const p=Math.min((t-start)/1400,1);setCount(Math.floor(p*value));if(p<1)frame=requestAnimationFrame(tick)};const el=document.getElementById("counter-"+value);const ob=new IntersectionObserver(([e])=>{if(e.isIntersecting){frame=requestAnimationFrame(tick);ob.disconnect()}},{threshold:.4});if(el)ob.observe(el);return()=>{cancelAnimationFrame(frame);ob.disconnect()}},[value]);return <span id={"counter-"+value}>{count}{suffix}</span>}

function Navbar({dark,setDark}){const[open,setOpen]=useState(false);const links=["Features","Process","Stories","Pricing","Contact"];return <header className="navbar"><a className="brand" href="#home" onClick={()=>setOpen(false)}><span className="brand-icon"><Sparkles size={17}/></span>NEXORA</a><nav className={"nav-links "+(open?"open":"")}>{links.map(l=><a key={l} href={"#"+l.toLowerCase()} onClick={()=>setOpen(false)}>{l}</a>)}</nav><div className="nav-actions"><button className="theme-btn" onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?<Sun size={17}/>:<Moon size={17}/>}</button><a className="nav-cta" href="#contact">Get started <ArrowUpRight size={15}/></a><button className="menu-btn" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?<X size={21}/>:<Menu size={21}/>}</button></div></header>}

export default function App(){
 const[dark,setDark]=useState(false),[form,setForm]=useState({name:"",email:"",message:""}),[sent,setSent]=useState(false);
 const{scrollYProgress}=useScroll();const progress=useSpring(scrollYProgress,{stiffness:120,damping:30});const heroY=useTransform(scrollYProgress,[0,.25],[0,-120]);const orbY=useTransform(scrollYProgress,[0,.5],[0,220]);
 const submit=e=>{e.preventDefault();if(!form.name.trim()||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)||!form.message.trim())return;setSent(true);setForm({name:"",email:"",message:""})};
 return <div className={"site "+(dark?"dark":"")}><motion.div className="scroll-progress" style={{scaleX:progress}}/><Navbar dark={dark} setDark={setDark}/><main>
 <section id="home" className="hero"><div className="hero-grid"/><motion.div className="hero-orb orb-one" style={{y:orbY}}/><motion.div className="hero-orb orb-two" style={{y:heroY}}/><motion.div className="hero-copy" style={{y:heroY}}>
 <Reveal><div className="pill"><Sparkles size={14}/> Intelligence, redesigned <span>NEW</span></div></Reveal><Reveal delay={.08}><h1>Build what's <em>next.</em><br/>With intelligent AI.</h1></Reveal><Reveal delay={.16}><p>Connect your data, automate your workflows and turn complex decisions into simple momentum.</p></Reveal><Reveal delay={.22}><div className="hero-actions"><a className="button primary" href="#contact">Start building <ArrowRight size={17}/></a><a className="button ghost" href="#features"><span className="play"><Play size={13} fill="currentColor"/></span>See how it works</a></div></Reveal><Reveal delay={.28}><div className="hero-note"><span className="avatars"><i>MC</i><i>DB</i><i>AP</i></span>Trusted by 2,000+ modern teams</div></Reveal></motion.div>
 <div className="hero-visual"><motion.div className="glass-card main-glass" initial={{opacity:0,y:40,rotateX:8}} animate={{opacity:1,y:0,rotateX:0}} transition={{duration:1,delay:.25}}><div className="glass-top"><span>AI WORKSPACE</span><span className="live-dot">● LIVE</span></div><div className="chart-title"><strong>Workflow performance</strong><span>Last 30 days</span></div><div className="mini-chart"><div className="chart-bars">{[35,48,42,67,58,75,64,88,72,94].map((h,i)=><i key={i} style={{height:h+"%"}}/>)}</div><div className="chart-line"><span/><span/><span/></div></div><div className="metric-row"><div><small>Automations</small><strong>12,840</strong><b>+24.8%</b></div><div><small>Time saved</small><strong>482h</strong><b>+31.2%</b></div></div></motion.div><motion.div className="floating-chip chip-one" animate={{y:[0,-10,0]}} transition={{duration:3,repeat:Infinity}}>⚡ 84% faster workflows</motion.div><motion.div className="floating-chip chip-two" animate={{y:[0,10,0]}} transition={{duration:4,repeat:Infinity}}>✓ AI task completed</motion.div></div>
 <a className="scroll-hint" href="#features"><span/>Scroll to explore <ChevronDown size={16}/></a></section>
 <section className="logo-strip"><p>POWERING TEAMS AT</p><div><b>orbit</b><b>northstar</b><b>vertex</b><b>lumio</b><b>MONO</b><b>arc</b></div></section>
 <section id="features" className="section"><Reveal><div className="section-head"><div><span className="kicker">01 / CAPABILITIES</span><h2>Everything you need to<br/><em>move faster.</em></h2></div><p>One intelligent platform that brings your people, processes and data together.</p></div></Reveal><div className="feature-grid">{features.map(({icon:Icon,title,text},i)=><Reveal key={title} delay={i*.08}><motion.article className="feature-card" whileHover={{y:-8}}><div className="feature-icon"><Icon size={21}/></div><span className="feature-number">0{i+1}</span><h3>{title}</h3><p>{text}</p><a href="#contact">Explore <ArrowUpRight size={15}/></a></motion.article></Reveal>)}</div></section>
 <section className="stats-section"><div className="section stats-inner"><Reveal><span className="kicker">02 / THE NUMBERS</span><h2>Built for <em>real impact.</em></h2></Reveal><div className="stats-grid">{[[10,"M+","AI tasks processed"],[99,".9%","platform uptime"],[180,"+","countries reached"],[4,"×","faster decisions"]].map(([v,s,t],i)=><Reveal key={t} delay={i*.05}><div><strong><Counter value={v} suffix={s}/></strong><span>{t}</span></div></Reveal>)}</div></div></section>
 <section className="parallax-section"><motion.div className="parallax-shape shape-a" style={{y:useTransform(scrollYProgress,[.35,.75],[100,-160])}}/><motion.div className="parallax-shape shape-b" style={{y:useTransform(scrollYProgress,[.35,.75],[-80,180])}}/><div className="parallax-content"><Reveal><span className="kicker">03 / INTELLIGENCE LAYER</span><h2>From scattered data<br/>to <em>clear direction.</em></h2><p>Nexora sits above your existing stack, turning signals into actions without asking your team to rebuild everything.</p><a className="button light" href="#process">See the process <ArrowRight size={16}/></a></Reveal></div></section>
 <section id="process" className="section"><Reveal><div className="section-head"><div><span className="kicker">04 / HOW IT WORKS</span><h2>A simpler path from<br/><em>idea to impact.</em></h2></div></div></Reveal><div className="timeline">{["Discover","Connect","Automate","Analyze","Grow"].map((step,i)=><Reveal key={step} delay={i*.08}><div className="timeline-item"><div className="timeline-dot">{String(i+1).padStart(2,"0")}</div><div><span>STEP {i+1}</span><h3>{step}</h3><p>{["Map your highest-value opportunities.","Bring your tools and data together.","Let AI handle repetitive decisions.","See what's working in real time.","Keep improving with intelligent feedback."][i]}</p></div></div></Reveal>)}</div></section>
 <section id="stories" className="section"><Reveal><div className="section-head"><div><span className="kicker">05 / CUSTOMER STORIES</span><h2>Loved by teams<br/><em>building forward.</em></h2></div></div></Reveal><div className="testimonial-grid">{testimonials.map((t,i)=><Reveal key={t.name} delay={i*.1}><motion.article className="testimonial-card" whileHover={{y:-7}}><Quote size={25}/><p>“{t.quote}”</p><div><div className="avatar">{t.name.split(" ").map(n=>n[0]).join("")}</div><strong>{t.name}</strong><span>{t.role}</span></div></motion.article></Reveal>)}</div></section>
 <section id="pricing" className="section"><Reveal><div className="section-head"><div><span className="kicker">06 / PRICING</span><h2>Start small.<br/><em>Scale without limits.</em></h2></div><p>Simple plans designed to grow with your ambition.</p></div></Reveal><div className="pricing-grid">{plans.map((p,i)=><Reveal key={p.name} delay={i*.08}><motion.article className={"price-card "+(p.featured?"featured":"")} whileHover={{y:-8}}><span className="plan-name">{p.name}</span><h3><sup>$</sup>{p.price}<small>/mo</small></h3><p>{p.text}</p><ul>{p.items.map(x=><li key={x}><Check size={15}/>{x}</li>)}</ul><a className={"button "+(p.featured?"primary":"ghost")} href="#contact">Choose {p.name} <ArrowRight size={15}/></a></motion.article></Reveal>)}</div></section>
 <section id="contact" className="contact-section"><div className="section contact-grid"><Reveal><span className="kicker">07 / LET'S TALK</span><h2>Ready to build<br/><em>what's next?</em></h2><p>Tell us what you're working on. We'll show you where intelligent automation can create the most leverage.</p><div className="contact-links"><a href="mailto:hello@nexora.ai">hello@nexora.ai</a><span>•</span><span>Available worldwide</span></div></Reveal><Reveal delay={.1}><form onSubmit={submit} className="contact-form"><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name" required/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@company.com" required/></label><label>Message<textarea value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder="Tell us about your project..." required/></label><button className="button primary" type="submit">{sent?"Message sent ✓":"Send message"} <ArrowRight size={16}/></button>{sent&&<p className="success">Thanks! Your message has been validated and captured.</p>}</form></Reveal></div></section>
 </main><footer><div className="brand"><span className="brand-icon"><Sparkles size={17}/></span>NEXORA</div><p>© 2026 Nexora. Intelligence for what's next.</p><a href="#home">Back to top ↑</a></footer></div>}
